export const quests = [
    {
        name : 'Беспорядки',
        questType : 'default',
        difficult : 'easy',
        type : 'kill',
        locationId : 24,
        location : 'Город драконов',
        npcName : 'Генерал Города Драконов',
        goal :
            [
                {targetName : 'Воин-драконоборец', quantity : 15},
                {targetName : 'Моб 2', quantity : 1225},
            ],
        exp : 4771,
        gold : 5726,
        spirit : 10880,
        point : [374, 221],
        levelRequest : 20,
        party : true,
        isDone : false,
    },
    {
        name : 'Квест 2',
        questType : 'default',
        difficult : 'easy',
        type : 'kill',
        locationId : 24,
        location : 'Город драконов',
        npcName : 'Генерал Города Драконов',
        goal :
            [
                {targetName : 'Воин-драконоборец', quantity : 15},
                {targetName : 'Воин-драконоборец', quantity : 1225},
            ],
        exp : 4771,
        gold : 5726,
        spirit : 10880,
        point : [374, 221],
        levelRequest : 20,
        party : true,
        isDone : false,
    },
    {
        name : 'Квест 3',
        questType : 'default',
        difficult : 'easy',
        type : 'kill',
        locationId : 24,
        location : 'Город драконов',
        npcName : 'Генерал Города Драконов',
        goal :
            [
                {targetName : 'Росянка', quantity : 15},
            ],
        exp : 4771,
        gold : 5726,
        spirit : 10880,
        point : [374, 221],
        levelRequest : 20,
        party : true,
        isDone : false,
    },
]